# Generated by Django 4.2.11 on 2024-09-13 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="hotel",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="hotel",
            name="postnumber",
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name="hotel",
            name="prefecture",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
